### ISSUE TITLE
Unable to add show

### ISSUE THREAD

**Issue by TryTryAgain** [MGaetan89/ShowsRage#95] opened 2016-08-18 00:09 UTC
## Bug report
- **_ShowsRage_ version:** 1.4.1
- **Device / Android version:** Nexus 6P / 6.0.1 and Nexus 7 original / running latest Cyanogenmod
### Issue description

Upon adding a show, no matter the destination (local disk volume and/or NFS), I get the following toast error:
'RootDir = [{defaultDir:0},{location:/path/to/downloadDir},{valid:1}]' is not a valid location

"/path/to/downloadDir" is of course an actual path, not this one used in the example.
I thought it may have been the folders contained spaces, tried with one that didn't still doesn't work. 

Am I missing some configuration on the Server side? Something on the ShowsRage side?
### Expected result

Show would be added to the selected destination with the chosen options
### Steps to reproduce
1. Click + to search for show
2. Click Show
3. Keep defaults, or change destination, and click add

**Comment by MGaetan89** [comment] 2016-08-20 10:22
This issue was reported a couple of time already, but I was not yet able to reproduce it.
I will do my best to find the cause and fix it in the next release.

**Comment by MGaetan89** [comment] 2016-08-20 13:36
I found the cause of this issue. The fix will be integrated soon and available in the next version of ShowsRage.
Thanks for reporting it.

**Closed as completed** 2016-08-20 14:35 UTC
Labels: Bug

**Comment by TryTryAgain** [comment] 2016-08-20 16:37
Fantastic, very much appreciated. Happy it was easily resolvable.
