### ISSUE TITLE
Log filter not working proper

### ISSUE THREAD

**Issue by fernandog** [MGaetan89/ShowsRage#101] opened 2016-08-23 23:24 UTC
## Bug report
- **_ShowsRage_ version:** latest beta from 23/08
- **Android version:** 4.2.2
- **Device:** Galaxy S4
### Issue description

Choose thread: FINDSUBTITLES
Change log level: DEBUG
### Expected result

Sees debug levels + info levels to FINDSUBTITLES only
Seems changing filter is reseting level
also changing level is reseting filter

**Comment by MGaetan89** [comment] 2016-08-24 05:40
I confirm that changing the log level reset the filter. I will fix it before the public release.
However, I am not sure about the first  point (changing filter is reseting level). I will check that.

**Comment by MGaetan89** [comment] 2016-08-25 18:26
I found the cause of the issue. It will be fixed when I release the public version 1.5.

**Comment by fernandog** [comment] 2016-08-25 18:33
@MGaetan89 thanks!
we fixed - thanks to @ratoaq2 Medusa log (PR still open) too so we won't see those bunch of API logs

**Comment by MGaetan89** [comment] 2016-08-25 18:35
I saw the PR yes, it's not a bad idea.
Will you still keep the "API Access granted" logs?

**Comment by fernandog** [comment] 2016-08-25 18:39
@MGaetan89 i dont think so. why do you need it?

I running ShowsRage with that branch and logs appear ok.

@ratoaq2 can confirm

**Comment by MGaetan89** [comment] 2016-08-26 17:46
I don't need. Just thought it might be useful to know when someone is accessing SickRage with the API.

**Comment by fernandog** [comment] 2016-08-26 17:48
@MGaetan89 do you have an APK so i can test the fix before pushing to play store?

**Comment by MGaetan89** [comment] 2016-08-26 17:50
Not yet. I can do an extra beta version first if you prefer.

**Comment by fernandog** [comment] 2016-08-26 17:52
Would be nice. Just to confirm its fixed.

**Comment by MGaetan89** [comment] 2016-08-26 18:02
I'm waiting for Travis result in https://github.com/MGaetan89/ShowsRage/pull/100 and then I'll push a new beta version on the Play Store.

**Comment by MGaetan89** [comment] 2016-08-26 19:44
I just pushed a new beta version. You should receive it in the next hour.

**Comment by fernandog** [comment] 2016-08-26 19:50
@MGaetan89 thanks! will let you know

**Comment by fernandog** [comment] 2016-08-26 20:06
Updated but still something is wrong:

From logs:
2016-08-26 16:37:43 INFO     FINDSUBTITLES :: [555b0cb] No subtitles to download
2016-08-26 16:37:43 INFO     FINDSUBTITLES :: [555b0cb] Checking for missed subtitles

ShowsRage:
3 days ago? Only INFO?

![screenshot_2016-08-26-17-03-16](https://cloud.githubusercontent.com/assets/2620870/18018788/4475765e-6baf-11e6-9a12-a2425ca34acc.png)

**Comment by fernandog** [comment] 2016-08-26 20:08
Another: see how log jumps from minutes to hours:

Is clearly mising a LOT of logs
![screenshot_2016-08-26-17-07-58](https://cloud.githubusercontent.com/assets/2620870/18018892/c1ef5c76-6baf-11e6-9008-1247dbe3d040.png)

**Comment by MGaetan89** [comment] 2016-08-28 08:25
I don't have time to properly investigate this issue for the moment, so I disable the logs filter until the next version.
Can you test the attached APK to see if you are still missing some logs? (GitHub does not support attaching APK, so I just changed the extension to zip. Change it back to apk before installing it).

[ShowsRage-v1.5](https://github.com/MGaetan89/ShowsRage/files/441044/app-release.zip)

**Comment by fernandog** [comment] 2016-08-28 11:06
It jumps from 1hour to 3 days

![screenshot_2016-08-28-08-04-36](https://cloud.githubusercontent.com/assets/2620870/18033289/34dd7d52-6cf6-11e6-95d6-6213446efe84.png)

**Comment by MGaetan89** [comment] 2016-08-28 11:35
I guess it's because I store logs locally, and don't clean them if they are cleared in SickRage (manually or after an update).
Does SickRage API returns more logs or does it only return two entries for INFO log level?
I will make sure that I only store what SickRage returns to prevent this.

**Comment by fernandog** [comment] 2016-08-28 12:18
imo you shouldn't store logs, just show what SickRage/Medusa sends.

**Comment by MGaetan89** [comment] 2016-08-28 12:23
I'm trying to stay feature-full when offline/disconnected from SickRage.
I updated the logs storage to better reflect what SickRage sends.

I am waiting for Travis to finish running the tests, and then I'll release the new version.

**Comment by MGaetan89** [comment] 2016-08-28 13:40
I'm closing this for now, as it is not part of version 1.5.
Don't hesitate to open a new issue for 1.6 if the problem if still there.

**Closed as completed by MGaetan89** 2016-08-28 13:40 UTC
Labels: Bug

**Comment by fernandog** [comment] 2016-12-03 18:48
@MGaetan89 looks like its working (i missed where you tagged me about the update so im writing here)

I noticed some old logs from 2 months ago. Refresh page doesn't make then go away (cached maybe?) only changing any filter
confirm?

personally i think caching log is not really needed.

**Comment by MGaetan89** [comment] 2016-12-10 15:24
Sorry for the delay...
Maybe try to refresh each log level (debug/info/warn/error) to see if old logs go away. If they don't. There might still be an issue.
