### ISSUE TITLE
Error on Sickrage API

### ISSUE THREAD

**Issue by monk-blade** [MGaetan89/ShowsRage#124] opened 2016-11-23 20:28 UTC
Thank you for contributing to *ShowsRage*. Please fill in the form corresponding to your request ("Bug report" or "Feature request"). The other sections can safely be removed.

## Bug report

* ***ShowsRage* version:** Git stable branch
* **Android version:** 6.1.1
* **Device:** Xiaomi Redmi 3S

### Issue description
Error log on Sickrage portal
   2016-11-23 15:21:02 API :: 'Core' object has no attribute 'STARTED'

API Key successfully received but connection fails.

**Comment by MGaetan89** [comment] 2016-11-26 10:49
This issue was already reported in #55, so I'm closing it to keep all discussion in one thread.
I was not able to reproduce this yet. So I don't know how to fix it in ShowsRage for the moment.

However, in the other issue, users seem to be able to work around the problem by changing the port SickRage is running on. Can you try that? If it does not work, don't hesitate to comment in the other issue.

**Closed as completed by MGaetan89** 2016-11-26 10:49 UTC
Labels: Bug, Duplicate

**Comment by monk-blade** [comment] 2016-11-26 11:59
Okay. Thanks.

**Comment by monk-blade** [comment] 2016-11-26 12:21
Default port is 8081 = error
Port changed to 5700 = error
😑
