### ISSUE TITLE
Cannot add new show (search returns no results)

### ISSUE THREAD

**Issue by binhex** [MGaetan89/ShowsRage#149] opened 2018-05-23 10:12 UTC
Thank you for contributing to *ShowsRage*. Please fill in the form corresponding to your request ("Bug report" or "Feature request"). The other sections can safely be removed.

## Bug report

* ***ShowsRage* version:** 1.6.1
* **Android version:** 7.0
* **Device:** Samsung Galaxy S7 Edge

### Issue description
When clicking on the + symbol i am presented with a search box, entering in the name of the show returns 'no results'.

Please note, this is connecting to Medusa ver 0.2.4 (SickRage fork) so it most probably is an incompatibility with the fork.

### Expected result
Results would be found and i could pick the correct show from the list.

### Steps to reproduce

1. click on +
2. Enter any TV series name
3. Note that no results are found

**Comment by MGaetan89** [comment] 2018-05-23 21:27
I'm also using Medusa, and I am able to reproduce the issue.
According to Medusa's API documentation, the request I use to perform the search seems to be correct. Maybe it is an issue in Medusa itself. I'll investigate more and check with the dev of Medusa.
I'll give you more info as soon as I know more.

**Comment by MGaetan89** [comment] 2018-05-26 09:16
There is an issue in Medusa's API.
It is being fixed, and will probably be part of the next release of Medusa.

**Comment by binhex** [comment] 2018-05-26 09:26
Excellent, thanks for looking into it.

**Comment by MGaetan89** [comment] 2018-06-10 18:13
Medusa 0.2.5 was just released, with a fix for this issue.
Don't hesitate to reopen it if you still have issues.

**Comment by binhex** [comment] 2018-06-10 20:21
I've updated to the latest Medusa release and I'm still seeing nothing retuned m afraid, after a few seconds of waiting Android then returns with the message "ShowsRage has stopped".

**Comment by MGaetan89** [comment] 2018-06-10 20:23
Indeed, I received the related crash report. I will fix it in the next version.
Sorry about that.

**Comment by binhex** [comment] 2018-06-11 08:21
hey no probs, thanks for looking into it, i appreciate it.

**Comment by MGaetan89** [comment] 2018-06-19 09:48
I fixed the issue. It will be part of version 1.7.
I will release it for beta users first for a few days, then to public.

If you want to test the new version during the beta phase, you can join the program [here](https://github.com/MGaetan89/ShowsRage#trying-the-application).

**Closed as completed by MGaetan89** 2018-06-19 09:48 UTC
Labels: Bug

**Comment by binhex** [comment] 2018-06-22 19:21
Thanks for this, I have actually signed up to beta testing but as of yet haven't seen an update, as soon as it does install I will test the change and let you know.

**Comment by MGaetan89** [comment] 2018-06-24 11:55
I just published the beta version. You should be able to install it soon.

**Comment by binhex** [comment] 2018-06-25 07:49
Thanks for your work, i can confirm i can now see results returned when adding in a show, and i can then select the show and i see it added to Medusa. i have noticed a couple more bugs that i will raise separately to this.

Thanks again.
