### ISSUE TITLE
Shows list empty

### ISSUE THREAD

**Issue by Coelen** [MGaetan89/ShowsRage#24] opened 2015-10-05 16:48 UTC
I've updated to the last version of both SickRage and ShowsRage I'm connected succesfully and the coming episodes list works as well. However, the shows screen is empty, not sure what might be the cause of it?

Showsrage V1.1
Sickrage version: BRANCH: (master) / COMMIT: (555ca46fa798c76d608827815816761116e19f02) running on my Synology DS213j.

**Comment by MGaetan89** [comment] 2015-10-05 19:27
Do you have something in your logs that might help find the cause of this issue?
Or is it possible that the list is just taking some time to load?
I just updated my SickRage to the latest version and I don't have any issue to display the list of shows.

**Comment by MGaetan89** [comment] 2015-10-08 06:23
I also have this issue and I think I know why it is happening.
However, it requires changes in SickRage to be fixed properly.
I will report the issue on there issue tracker so they are aware of the issue.

For me, it happened because I paused/unpaused a show from the application and now the API returns a different data.

**Comment by benyjr** [comment] 2015-10-08 19:38
I found that this issue happens for me when I add a show through ShowsRage.

**Comment by MGaetan89** [comment] 2015-10-08 19:44
Thanks for the info. When adding the show, did you enable the "anime" and/or the "subtitle" option?

**Comment by benyjr** [comment] 2015-10-08 19:45
No, I didn't.

**Comment by MGaetan89** [comment] 2015-10-08 19:51
Can you access SickRage's API builder (by replacing `/home` with `/apibuilder` in your SickRage URL), run the `shows` command (near the bottom of the page) and send me the part about the show that might be causing the issue?
It should look something like this:

``` json
{
    "air_by_date": 0,
    "anime": 0,
    "cache": {
        "banner": 1,
        "poster": 1
    },
    "indexerid": 248741,
    "language": "en",
    "network": "CBS",
    "next_ep_airdate": "",
    "paused": 0,
    "quality": "HD1080p",
    "show_name": "2 Broke Girls",
    "sports": 0,
    "status": "Continuing",
    "subtitles": 0,
    "tvdbid": 248741
}
```

**Comment by benyjr** [comment] 2015-10-08 19:53
Right now, I can't because I'm at work. I will try later tonight.

**Comment by benyjr** [comment] 2015-10-08 20:03
Here you go:

"75760": {
            "air_by_date": 0,
            "anime": 0,
            "cache": {
                "banner": 1,
                "poster": 1
            },
            "indexerid": 75760,
            "language": "en",
            "network": "CBS",
            "next_ep_airdate": "",
            "paused": 0,
            "quality": "SD",
            "show_name": "How I Met Your Mother",
            "sports": 0,
            "status": "Ended",
            "subtitles": false,
            "tvdbid": 75760
        },

**Comment by MGaetan89** [comment] 2015-10-08 20:06
Didn't have to wait too long :P

This confirm what I thought. For some reason, boolean values are returned in the wrong format.
If I have time, I will fix it next week.
Thanks for your help.

**Comment by benyjr** [comment] 2015-10-08 20:07
You are welcome.

Turns out the guest wifi at work doesn't block my SickRage ports. :-D

**Comment by MGaetan89** [comment] 2015-10-09 19:42
This is now fixed in the `develop` branch of SickRage.
It will be available in the next release of SickRage.

**Comment by MGaetan89** [comment] 2015-10-10 06:45
The fix is in the latest release and it's working for me.
Can you confirm that it's working for you too?

**Comment by benyjr** [comment] 2015-10-10 21:39
Seems to work when I am on my own network. I will test it again when I am on a remote network.

**Comment by MGaetan89** [comment] 2015-10-12 17:20
Did you manage to test from a remote network yet?

**Comment by benyjr** [comment] 2015-10-12 17:28
Thanks for the reminder. 

I just tested it and it seems to be working.

**Comment by MGaetan89** [comment] 2015-10-12 17:30
Thanks. Glad it's working again :)

**Closed as completed by MGaetan89** 2015-10-12 17:30 UTC
Labels: SickRage
