### ISSUE TITLE
Various colours for status labels

### ISSUE THREAD

**Issue by bertenvdb** [MGaetan89/ShowsRage#58] opened 2016-02-03 06:24 UTC
In the season overview, the colour of the status labels is always green. 
I would prefer having the same colours as in SickRage. Green for downloaded, orange for snatched and blue for skipped.

**Comment by MGaetan89** [comment] 2016-02-03 22:08
This should already be the case. Can you post a screenshot?
Maybe give some details about your configuration as well: application version, Android version and device.

**Comment by MGaetan89** [comment] 2016-02-20 15:26
Closing, as this seem to be working as intended.

**Comment by bertenvdb** [comment] 2016-02-20 17:15
Apologies @MGaetan89 , completely forgot about this.

Strange, after closing the app and reopening, some labels sometimes have another color than before. E.g. scrot 3 and 4 show same season/eps but different colours.

Samsung Galaxy Fresh GT-S7390
Android 4.1.2
ShowsRage 1.3
SickRage 2016.02.16-1

![screenshot_2016-02-20-17-48-12](https://cloud.githubusercontent.com/assets/1568251/13197941/36304354-d7fc-11e5-833b-8b96835f2839.png)
![screenshot_2016-02-20-17-48-25](https://cloud.githubusercontent.com/assets/1568251/13197943/36530bc8-d7fc-11e5-8486-9256642921ad.png)
![screenshot_2016-02-20-17-48-49](https://cloud.githubusercontent.com/assets/1568251/13197942/36516ce6-d7fc-11e5-8f9e-f9b84f43a6d9.png)
![screenshot_2016-02-20-18-10-02](https://cloud.githubusercontent.com/assets/1568251/13198015/ce48cb10-d7fd-11e5-9337-2858235296cf.png)

**Comment by MGaetan89** [comment] 2016-02-20 17:56
Thanks for the details. I managed to reproduce this in an emulator using Android 4.1.2.
I will work to fix it in the next version.

**Comment by MGaetan89** [comment] 2016-02-27 11:19
It seems to be fixed in the latest development version. At least I can no longer reproduce it.
I keep this issue open until the next release so you can confirm if it is fixed or not.

**Comment by MGaetan89** [comment] 2016-02-29 19:42
I found a device where I can reproduce this bug.
It happens in the latest stable version (1.3), but it is working fine in the latest development version (1.4).
So I'm closing this issue. If you still have this problem with the next release, let me know.

**Closed as completed by MGaetan89** 2016-02-29 19:42 UTC
Labels: Bug
